import  = ["~/.config/alacritty/gruvbox_material_medium_dark.toml"]

[window]
opacity = 0.999
padding = { x = 5, y = 3 }
option_as_alt = "Both"

[font]
size = 13
normal = { family = "FiraCode Nerd Font", style = "Regular" }
